### ISSUE TITLE
Cannot install v3.0.7

### ISSUE THREAD

**Issue by fgvieira** [lanzen/CREST#6]
Dear all,

I'm trying to install LCAClassfiier, but it is not working:
```
[LCAClassifier]$ ./install.sh 
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Creating directory 'LCAClassifier/eggs'.
Creating directory 'LCAClassifier/bin'.
Creating directory 'LCAClassifier/parts'.
Creating directory 'LCAClassifier/develop-eggs'.
Generated script 'LCAClassifier/bin/buildout'.
Getting distribution for 'zc.buildout==2.9.5'.
Got zc.buildout 2.9.5.
Upgraded:
  zc.buildout version 2.9.5;
restarting.
Generated script 'LCAClassifier/bin/buildout'.
Upgraded:
  zc.buildout version 2.9.5;
restarting.
Upgraded:
  zc.buildout version 2.9.5;
restarting.
Upgraded:
  zc.buildout version 2.9.5;
restarting.
Upgraded:
  zc.buildout version 2.9.5;
restarting.
[...]
```

it just goes on and on....
any idea on how I can fix it?

thanks,

**Comment by lanzen** [comment]
Hi,

If you follow the link in the start of your error message, you get some more information about this particular error, which is a case of setuptools not being able to  install itself. It should be possible to solve by installing setuptools before trying to install CREST, in which case CREST will not attempt to install it and you should not get the strange infinite loop that you have seen (this was a new issue for me, but I have seen hundreds of bugs caused by setuptools which unfortunately does not seem very stable and I am planning to drop it from CREST, but I have just not had time to completely change the installation procedure). 

Try "pip install setuptools" then runn install.sh in CREST again and that might work. If not, please let me know.

Cheers,
Anders

**Comment by fgvieira** [comment]
Hi Anders,

thanks for your help on this but, unfortunately, I don't think it worked:
```
$ pip install setuptools
Requirement already satisfied: setuptools in /software/python/v2.7.12/lib/python2.7/site-packages (39.1.0)
$ ./install.sh 
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Creating directory 'LCAClassifier/eggs'.
Creating directory 'LCAClassifier/bin'.
Creating directory 'LCAClassifier/parts'.
Creating directory 'LCAClassifier/develop-eggs'.
Generated script 'LCAClassifier/bin/buildout'.
Getting distribution for 'zc.buildout==2.9.5'.
Got zc.buildout 2.9.5.
Upgraded:
  zc.buildout version 2.9.5;
restarting.
Generated script 'LCAClassifier/bin/buildout'.
Upgraded:
  zc.buildout version 2.9.5;
restarting.
Upgraded:
  zc.buildout version 2.9.5;
restarting.
Upgraded:
  zc.buildout version 2.9.5;
restarting.
```

thanks,

**Comment by lanzen** [comment]
Are you running Ubuntu or Debian? Then you could also try apt install python-zc.buildout.

However, it may be that you have to install an older version of setuptools to make it possible, specifically 33.1.1 or older. This is really messy and I am sorry for it, but unfortunately there is not much I can do short of re-writing large parts of the code base since the configuration of the LCAClassifier depends on setuptools. The problem is that CREST is something I did during my PhD thesis five years ago and I now have very little time to improve it, and the time I have is best used to improve the SilvaMod database itself. I am also planning on adding support for EukRef or PR2, and CO1 amplicons.

Best,
Anders

**Comment by fgvieira** [comment]
I am using CentOS.

I tried installing an older version of `setuptools`:
`pip install 'setuptools==33.1.0`
but got the same error.

I then tried to also install an older version of zc.buildout:
`pip install 'zc.buildout==2.9.5'`

And with that I managed to install it, even though with some warnings:
```
$ ./install.sh
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip
Extracting in /tmp/tmpEtfnnq
Now working in /tmp/tmpEtfnnq/setuptools-33.1.1
Building a Setuptools egg in /tmp/bootstrap-MRWVAP
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/bootstrap-MRWVAP/setuptools-33.1.1-py2.7.egg
no previously-included directories found matching 'doc'
no previously-included directories found matching 'old-tutorial'
Traceback (most recent call last):
  File "bootstrap.py", line 199, in <module>
    ws.require(requirement)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 963, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 854, in resolve
pkg_resources.VersionConflict: (zc.buildout 2.9.5 (/software/python/v2.7.12/lib/python2.7/site-packages), Requirement.parse('zc.buildout==2.11.4'))
Upgraded:
  zc.buildout version 2.9.5;
restarting.
Generated script 'v3.0.7/bin/buildout'.
Develop: 'v3.0.7/.'
Getting distribution for 'zc.recipe.testrunner'.
zip_safe flag not set; analyzing archive contents...
Got zc.recipe.testrunner 2.0.0.
Getting distribution for 'zc.recipe.egg>=1.2.0,>=2.0.0a3'.
Got zc.recipe.egg 2.0.5.
Getting distribution for 'zope.testrunner'.
package init file 'src/zope/testrunner/tests/testrunner-ex/__init__.py' not found (or not a regular file)
Got zope.testrunner 4.8.1.
Getting distribution for 'zope.exceptions'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Got zope.exceptions 4.2.0.
Getting distribution for 'z3c.recipe.template'.
Got z3c.recipe.template 0.1.
Getting distribution for 'z3c.recipe.mkdir'.
Got z3c.recipe.mkdir 0.6.
Getting distribution for 'hexagonit.recipe.download'.
Got hexagonit.recipe.download 1.7.1.
Installing test.
Getting distribution for 'biom-format==1.3.1'.
zip_safe flag not set; analyzing archive contents...
biom.util: module references __file__
Got biom-format 1.3.1.
Getting distribution for 'pyqi==0.3.1'.
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '.git' found anywhere in distribution
zip_safe flag not set; analyzing archive contents...
pyqi.commands.make_release: module references __file__
pyqi.core.interface: module references __file__
Got pyqi 0.3.1.
Generated script 'v3.0.7/bin/test'.
Installing lcaclassifier.
Generated script 'v3.0.7/bin/nds2CREST'.
Generated script 'v3.0.7/bin/classify'.
Generated interpreter 'v3.0.7/bin/python'.
Installing lcaclassifier_conf.
Installing mkdirs.
mkdirs: created path: v3.0.7/parts/flatdb
Installing silvamod.
Downloading http://services.cbu.uib.no/supplementary/crest/silvamod128.tar.gz
silvamod: Extracting package to v3.0.7/parts/flatdb
Installing greengenes.
Downloading http://services.cbu.uib.no/supplementary/crest/greengenes.tar.gz
greengenes: Extracting package to v3.0.7/parts/flatdb
Installing unite.
Downloading http://services.cbu.uib.no/supplementary/crest/unite.tar.gz
unite: Extracting package to v3.0.7/parts/flatdb
Installing amoa.
Downloading http://services.cbu.uib.no/supplementary/crest/amoA_CREST_v0.7_20171118.tar.gz
amoa: Extracting package to v3.0.7/parts/flatdb```

**Comment by lanzen** [comment]
Thank you for your patience and effort, and for letting me know in case other users have this problem, and sorry about the messy state of the installation requirements.

Best wishes and please let me know if you have any other issues with CREST or want help to interpret the results.

Anders

**Comment by sara45450** [comment]
Hi
I installed the setup tool33.1.1, but when I'm trying  to install it is not working.OS:ubuntu 15.10-64bit on VMware
./install.sh
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip
Extracting in /tmp/tmp9089x1we
Now working in /tmp/tmp9089x1we/setuptools-33.1.1
Building a Setuptools egg in /tmp/bootstrap-qrw6y770
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/bootstrap-qrw6y770/setuptools-33.1.1-py3.4.egg

**Comment by lanzen** [comment]
Hi Sara,

Is it important that you run VMware on the old 15.10 verison of Ubuntu, or could you first try to install CREST in a more up-to-date VM, e.g. 16.04 or newer? If that also does not work, please let me know and I will have a closer look. Without understanding what has happened, I get a feeling that your setuptools installation did not work as it should because of the strange warning message  (no files found matching '*' under directory 'setuptools/_vendor')

Best wishes,
Anders

**Comment by sara45450** [comment]
Thank you
The problem was solved by installing Ubuntu18, but a new one was created.i update all file on LCAClassifier.
./install.sh
Traceback (most recent call last):
  File "bootstrap.py", line 88, in <module>
    exec(urlopen('https://bootstrap.pypa.io/ez_setup.py').read(), ez)
  File "<string>", line 24, in <module>
ImportError: cannot import name 'log'
./install.sh: line 2: bin/buildout: No such file or directory
